const data = {
    users: [
        {
            name: 'Mahbubur Rahman',
            email: 'mahbub.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Afroza Afrin Liza',
            email: 'liza.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Nazmul Hasan',
            email: 'nazmul.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Abul Kalam Azad',
            email: 'abul.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Babul Mia',
            email: 'babul.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Camelia Akter',
            email: 'cemelia.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Dipu Biswas',
            email: 'dipu.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
        },
        {
            name: 'Emon Khan',
            email: 'emon.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Farzana Akter',
            email: 'farzana.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Golam Rabbani',
            email: 'rabbani.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
        {
            name: 'Habibur Rahman',
            email: 'habib.cse.me@gmail.com',
            password: 'Admin@123',
            address: 'Dhaka',
            phone: '01700000000',
            image: 'dummy.jpg',
        },
    ],
};

module.exports = data;